# Prefix & Mouse
set -g prefix C-a
unbind C-b
bind C-a send-prefix
set -g mouse on

# Status bar position
set -g status-position top

# True colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",tmux-256color:Tc"

# Index starting at 1
set -g base-index 1
setw -g pane-base-index 1

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# PATH for Homebrew
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin"

# Status Bar
set -g status on
set -g status-style bg=default,fg=default
set -g status-interval 1
set -g status-justify left

set -g window-status-current-format "#[fg=#ebdbb2,bold bg=#af3a03] #{window_index}:#W "
set -g window-status-format "#[fg=#ebdbb4,bg=#a89984] #{window_index}:#W "
set -g window-status-separator ""

set -g status-left-length 40
set -g status-left-style default
set -g status-left "#{?client_prefix,⬇️,}#[fg=#FFFFFF,bold,bg=#7F6E63] #S "

set -g status-right-length 40
set -g status-right-style default
set -g status-right "#[fg=#ffffff,bold bg=#a89984] %d %b %H:%M "

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

unbind t
bind t split-window -v -l 15 -c "#{pane_current_path}"

bind r source-file $HOME/.tmux.conf

# Keep this line at the bottom
run '~/.tmux/plugins/tpm/tpm'
